export const texts = {
  actions: "Akce",
  active: "Aktivní",
  add: "Přidat",
  addUser: "Přidat uživatele",
  admin: "Administrátor",
  addOrdinanceManually: "Přidat vyhlášku ručně",
  addOrdinance: "Přidat vyhlášku",
  addOrdinanceFromCollection: "Přidat vyhlášku ze sbírky právních předpisů",
  addressPoints: "Adresní místa",
  approvedAt: "Datum schválení",
  author: "Autor",
  cancel: "Zrušit",
  catchmentAreas: "Spádové oblasti",
  city: "Město",
  comment: "Komentář",
  confirm: "Potvrdit",
  counties: "Okresy",
  county: "Okres",
  delete: "Smazat",
  deleteOrdinanceTitle: "Smazat vyhlášku",
  deleteOrdinanceMessage: "Opravdu chcete smazat vybranou vyhlášku?",
  downloadJson: "Stáhnout JSON",
  downloadOrdinanceDocument: "Stáhnout dokument vyhlášky",
  edit: "Upravit",
  editedAt: "Datum úpravy",
  editHistory: "Historie úprav",
  editOrdinance: "Upravit vyhlášku",
  editOrdinanceText: "Upravit text vyhlášky",
  editUser: "Upravit uživatele",
  email: "E-mail",
  emailVerified: "E-mail ověřen",
  fillOutEmail: "Vyplňte e-mail...",
  fillOutFirstName: "Vyplňte jméno...",
  fillOutLastName: "Vyplňte příjmení...",
  fillOutName: "Vyplňte název...",
  fillOutPassword: "Vyplňte heslo...",
  firstName: "Jméno",
  founderNotFound: "Zřizovatel nenalezen.",
  founders: "Zřizovatelé",
  fullName: "Jméno a příjmení",
  gpt: "GPT",
  ico: "IČO",
  lastName: "Příjmení",
  logout: "Odhlásit se",
  map: "Mapa",
  mapForPublic: "Mapa pro veřejnost",
  name: "Název",
  no: "Ne",
  noData: "Nebyla nalezena žádná data k zobrazení",
  noDataOrdinanceFromRegister:
    "Obec {{city}} nemá ve Sbírce právních předpisů nahranou žádnou vyhlášku.",
  numberOfSchools: "Počet škol",
  ordinanceDocument: "Dokument vyhlášky",
  ordinanceFile: "Soubor vyhlášky",
  ordinanceName: "Název vyhlášky",
  ordinanceNumber: "Číslo vyhlášky",
  ordinances: "Vyhlášky",
  ordinanceUploaded: "Vyhláška nahrána",
  originalText: "Původní text",
  orp: "ORP",
  password: "Heslo",
  polygons: "Oblasti",
  publishedAt: "Datum zveřejnění",
  region: "Kraj",
  regions: "Kraje",
  requiredField: "Toto pole je povinné.",
  requiredFile: "Vyberte prosím soubor.",
  requiredOrdinanceNumber:
    "Vyplňte prosím číslo vyhlášky (ve formátu číslo/rok, např. 3/2019).",
  requiredValidToAfterValidFrom:
    "Datum konce platnosti musí být později než datum začátku platnosti.",
  role: "Role",
  save: "Uložit",
  saved: "Uloženo",
  saving: "Ukládání...",
  schoolEditorLabel: "škola",
  schools: "Školy",
  selectDate: "Vyberte datum...",
  setAsInProgress: 'Označit jako "Rozpracováno"',
  setAsPublished: 'Označit jako "Zveřejněno"',
  shortName: "Zkratka",
  statusInProgress: "Rozpracováno",
  statusNoActiveOrdinance: "Bez platné vyhlášky",
  statusNoOrdinance: "Bez vyhlášky",
  statusPublished: "Zveřejněno",
  streetEditorLabel: "ulice",
  status: "Stav",
  unverified: "Neověřený",
  url: "URL",
  unknownStatus: "Neznámý stav",
  unmappedAddressPoints: "Neurčená adresní místa",
  user: "Uživatel",
  users: "Uživatelé",
  valid: "Platná",
  validFrom: "Platnost od",
  validTo: "Platnost do",
  version: "Verze",
  viewOnMap: "Zobrazit na mapě",
  yes: "Ano",
};

export const replacePlaceholders = (
  text: string,
  placeholders: Record<string, string>
) => {
  let result = text;
  Object.keys(placeholders).forEach((key) => {
    result = result.replace(`{{${key}}}`, placeholders[key]);
  });
  return result;
};
