const texts = {
  actions: "Akce",
  active: "Aktivní",
  add: "Přidat",
  addUser: "Přidat uživatele",
  admin: "Administrátor",
  addOrdinanceManually: "Přidat vyhlášku ručně",
  addOrdinance: "Přidat vyhlášku",
  addOrdinanceFromCollection: "Přidat vyhlášku ze sbírky právních předpisů",
  approvedAt: "Datum schválení",
  author: "Autor",
  catchmentAreas: "Spádové oblasti",
  city: "Město",
  comment: "Komentář",
  counties: "Okresy",
  county: "Okres",
  delete: "Smazat",
  downloadJson: "Stáhnout JSON",
  downloadOrdinanceDocument: "Stáhnout dokument vyhlášky",
  edit: "Upravit",
  editedAt: "Datum úpravy",
  editHistory: "Historie úprav",
  editOrdinance: "Upravit vyhlášku",
  editOrdinanceText: "Upravit text vyhlášky",
  editUser: "Upravit uživatele",
  email: "E-mail",
  emailVerified: "E-mail ověřen",
  fillOutEmail: "Vyplňte e-mail...",
  fillOutFirstName: "Vyplňte jméno...",
  fillOutLastName: "Vyplňte příjmení...",
  fillOutName: "Vyplňte název...",
  fillOutPassword: "Vyplňte heslo...",
  firstName: "Jméno",
  founderNotFound: "Zřizovatel nenalezen.",
  founders: "Zřizovatelé",
  fullName: "Jméno a příjmení",
  ico: "IČO",
  lastName: "Příjmení",
  logout: "Odhlásit se",
  map: "Mapa",
  name: "Název",
  no: "Ne",
  numberOfSchools: "Počet škol",
  ordinanceDocument: "Dokument vyhlášky",
  ordinanceName: "Název vyhlášky",
  ordinanceNumber: "Číslo vyhlášky",
  ordinances: "Vyhlášky",
  originalText: "Původní text",
  orp: "ORP",
  password: "Heslo",
  publishedAt: "Datum zveřejnění",
  region: "Kraj",
  regions: "Kraje",
  role: "Role",
  save: "Uložit",
  saved: "Uloženo",
  saving: "Ukládání...",
  schoolEditorLabel: "škola",
  selectDate: "Vyberte datum...",
  shortName: "Zkratka",
  streetEditorLabel: "ulice",
  status: "Stav",
  unverified: "Neověřený",
  url: "URL",
  user: "Uživatel",
  users: "Uživatelé",
  valid: "Platná",
  validFrom: "Platnost od",
  validTo: "Platnost do",
  version: "Verze",
  viewOnMap: "Zobrazit na mapě",
  yes: "Ano",
};

export { texts };
