"use client";

import "./globals.css";
import { Inter } from "next/font/google";
import React, { useState } from "react";
import { usePathname } from "next/navigation";
import Appbar from "@/components/layout/Appbar";
import Navbar from "@/components/layout/Navbar";
import UserMenu from "@/components/layout/UserMenu";
import Providers from "@/providers/Providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [isNavbarOpen, setIsNavbarOpen] = useState(false);
  const pathname = usePathname();

  const toggleNavbar = () => {
    setIsNavbarOpen(!isNavbarOpen);
  };

  return (
    <html lang="en">
      <body className={`${inter.className} flex`}>
        {pathname === "/login" ? (
          <div className="grow flex flex-col">
            <main className="bg-slate-50 p-10 grow flex flex-col h-screen">
              {children}
            </main>
          </div>
        ) : (
          <Providers>
            <Navbar
              className={`${
                isNavbarOpen ? "w-64" : "w-0"
              } ease-in-out duration-150 h-screen`}
            ></Navbar>
            <div className="grow flex flex-col">
              <Appbar toggleNavbar={toggleNavbar}>
                <UserMenu />
              </Appbar>
              <main className="bg-slate-50 p-10 grow flex flex-col">
                {children}
              </main>
            </div>
          </Providers>
        )}
      </body>
    </html>
  );
}
