const texts = {
  active: "Aktivní",
  add: "Přidat",
  addOrdinanceManually: "Přidat vyhlášku ručně",
  addOrdinance: "Přidat vyhlášku",
  addOrdinanceFromCollection: "Přidat vyhlášku ze sbírky právních předpisů",
  author: "Autor",
  comment: "Komentář",
  county: "Okres",
  downloadJson: "Stáhnout JSON",
  edited: "Datum úpravy",
  editHistory: "Historie úprav",
  editOrdinance: "Upravit vyhlášku",
  editOrdinanceText: "Upravit text vyhlášky",
  founders: "Zřizovatelé",
  ico: "IČO",
  logout: "Odhlásit se",
  map: "Mapa",
  name: "Název",
  no: "Ne",
  numberOfSchools: "Počet škol",
  ordinanceName: "Název vyhlášky",
  ordinances: "Vyhlášky",
  orp: "ORP",
  region: "Kraj",
  regions: "Kraje",
  selectDate: "Vyberte datum",
  status: "Stav",
  fillOutName: "Vyplňte název",
  url: "URL",
  validFrom: "Platnost od",
  validTo: "Platnost do",
  viewOnMap: "Zobrazit na mapě",
  yes: "Ano",
};

export { texts };
