const texts  = {
  active: 'Aktivní',
  add: 'Přidat',
  addOrdinanceManually: 'Přidat vyhlášku ručně',
  addOrdinance: 'Přidat vyhlášku',
  addOrdinanceFromCollection: 'Přidat vyhlášku ze sbírky právních předpisů',
  approvedAt: 'Datum schválení',
  author: 'Autor',
  city: 'Město',
  comment: 'Komentář',
  county: 'Okres',
  downloadJson: 'Stáhnout JSON',
  edited: 'Datum úpravy',
  editHistory: 'Historie úprav',
  editOrdinance: 'Upravit vyhlášku',
  editOrdinanceText: 'Upravit text vyhlášky',
  founders: 'Zřizovatelé',
  ico: 'IČO',
  logout: 'Odhlásit se',
  map: 'Mapa',
  name: 'Název',
  no: 'Ne',
  numberOfSchools: 'Počet škol',
  ordinanceName: 'Název vyhlášky',
  ordinanceNumber: 'Číslo vyhlášky',
  ordinances: 'Vyhlášky',
  orp: 'ORP',
  publishedAt: 'Datum zveřejnění',
  region: 'Kraj',
  regions: 'Kraje',
  selectDate: 'Vyberte datum',
  status: 'Stav',
  fillOutName: 'Vyplňte název',
  url: 'URL',
  valid: 'Platná',
  validFrom: 'Platnost od',
  validTo: 'Platnost do',
  version: 'Verze',
  viewOnMap: 'Zobrazit na mapě',
  yes: 'Ano',
}

export { texts };
