"use client";

import dynamic from "next/dynamic";
import Head from "next/head";
import { useMemo } from "react";
import { Municipality } from "text-to-map";
import Spinner from "@/components/common/Spinner";

export interface CatchmentMapProps {
  municipalities: Municipality[];
}

export default function CatchmentMap({ municipalities }: CatchmentMapProps) {
  const Map = useMemo(
    () =>
      dynamic(() => import("@/components/map/InnerMap"), {
        loading: () => <Spinner />,
        ssr: false,
      }),
    []
  );

  return (
    <>
      <Head>
        <title>Mapa pražských spádových oblastí</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        <Map
          municipalities={municipalities}
        />
      </main>
    </>
  );
}
